package com.github.jmodel.adapter.api;

/**
 * The Adapter concept is used in mutable business application context. For
 * example, a complex log mechnism is required: related information generated by
 * transaction need to be stored in database, be dispatched to message queue at
 * the same time, even be sent someone by email. In such a situation, changing
 * skeleton of business logic is not a good solution. In order to keep main
 * program part unchanged, it is worth to introduce logger adapter concept. In
 * addition, the third party logger lib you choosed could be replaced by
 * something else for some reason.
 * <p>
 * The Adapter concept is important for program portability. The implementation
 * of common features (e.g. log, validation, model mapping, integration) is
 * removed from main program part. In other words, you can use the concepts and
 * ignore the implementation really.
 * 
 * @author jianni@hotmail.com
 *
 */
public interface Adapter {

}
